// Logos de simple-icons (CC0). Importados uno a uno para no cargar la librería entera.
import {
  siAngular,
  siAstro,
  siDocker,
  siGit,
  siGithubactions,
  siJira,
  siJsonwebtokens,
  siModelcontextprotocol,
  siMongodb,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPostgresql,
  siPostman,
  siReact,
  siSwagger,
  siTailwindcss,
  siTypescript,
} from "simple-icons";

export const ICONS: Record<string, { path: string; title: string }> = {
  angular: siAngular,
  astro: siAstro,
  docker: siDocker,
  git: siGit,
  githubactions: siGithubactions,
  jira: siJira,
  jsonwebtokens: siJsonwebtokens,
  modelcontextprotocol: siModelcontextprotocol,
  mongodb: siMongodb,
  nestjs: siNestjs,
  nextdotjs: siNextdotjs,
  nginx: siNginx,
  nodedotjs: siNodedotjs,
  postgresql: siPostgresql,
  postman: siPostman,
  react: siReact,
  swagger: siSwagger,
  tailwindcss: siTailwindcss,
  typescript: siTypescript,
};
